version: '3'
services:
  redis:
    container_name: redis-cache
    hostname: redis-server
    image: redis:6.2-alpine
    volumes:
      - cache:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis-server:6379
    ports:
    - "8081:8081"
volumes:
  cache: